### ISSUE TITLE
Image path reference issue when uploading multiple repositories.

### ISSUE THREAD

**Issue by SUN-SZY** [ylc395/joplin-plugin-pages-publisher#10]
### Image path reference issue when uploading multiple repositories.

The image path location of the page referenced by the **joplin-plugin-pages-publisher** plugin is an absolute path. In a github project, if it is not uploaded in the root directory, or if multiple sites are generated, the reference address of the reference is invalid, the reason for the invalidity is that the location of the reference image is under the root directory, how can I modify the path of the image reference, or can I add this change in the new update?It's like`/ `and `./`.

**Comment by ylc395** [comment]
> if it is not uploaded in the root directory, or if multiple sites are generated

maybe this plugin is not designed for these scenarios...
