### ISSUE TITLE
How to add config file in the root folder?

### ISSUE THREAD

**Issue by dudukee** [ylc395/joplin-plugin-pages-publisher#11]
Thx for your awesome plugin. 

When I deploy on vercel, sub page return 404 error, I should create a config file `vercel.json` in root folder and add some config in it. 

I created a theme folder, and add this .json in the theme folder, but when i generated pages, the .json missed.

So how to add config file in the root folder? Could U please share some idea for me.

**Comment by ylc395** [comment]
[ylc395.pagesPublisher.jpl.zip](https://github.com/ylc395/joplin-plugin-pages-publisher/files/8130225/ylc395.pagesPublisher.jpl.zip)

Try this version to see whether `vercel.json` will be copyed into generated directory. If it works, I will release it as new version.

**Comment by dudukee** [comment]
@ylc395 it not worked

**Comment by ylc395** [comment]
[ylc395.pagesPublisher.jpl.zip](https://github.com/ylc395/joplin-plugin-pages-publisher/files/8131018/ylc395.pagesPublisher.jpl.zip)

What about this? @dudukee

**Comment by dudukee** [comment]
It works as expected ! thx for your work! @ylc395

**Comment by dudukee** [comment]
`vercel.json` copyed into generated directory , BUT the `main.css` in the `_assets` disappeared :joy:

**Comment by ylc395** [comment]
[ylc395.pagesPublisher.jpl.zip](https://github.com/ylc395/joplin-plugin-pages-publisher/files/8131821/ylc395.pagesPublisher.jpl.zip)

This would work I promise.

**Comment by dudukee** [comment]
YES it works as expected, thx for your work!

**Comment by ylc395** [comment]
add this feature in v1.7.0
