### ISSUE TITLE
line breaks are not rendered like what is rendered in joplin

### ISSUE THREAD

**Issue by abbychau** [ylc395/joplin-plugin-pages-publisher#16]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/350283/184576158-711b0aeb-e216-4b7e-9709-5e15078f59e7.png">

In joplin desktop, line breaks can be rendered like gfm-favoured

but in publisher, it is rendered like this

<img width="538" alt="image" src="https://user-images.githubusercontent.com/350283/184576234-589575b1-a3cd-4811-b63d-6cd650efd358.png">

any idea how to fix it / make it like gfm-favoured?

**Comment by ylc395** [comment]
fixed in version 1.7.1
