### ISSUE TITLE
Can it read the tags of notes and generate a tag list that links to different articles?

### ISSUE THREAD

**Issue by abbychau** [ylc395/joplin-plugin-pages-publisher#17]
As title.

**Comment by ylc395** [comment]
Yes. You can make your own theme.

see https://github.com/ylc395/joplin-plugin-pages-publisher/wiki/How-to-create-a-custom-theme#env-variables-for-a-page

**Comment by abbychau** [comment]
I found that I can only access tags in each of the article page. i don't know how to keep the state and generate a tag cloud.

are there any templates that are already aggregating tags for my reference?

**Comment by ylc395** [comment]
> I found that I can only access tags in each of the article page. i don't know how to keep the state and generate a tag cloud.
> 
> are there any templates that are already aggregating tags for my reference?

https://discourse.joplinapp.org/t/plugin-generate-static-blog-website-and-publish-to-github-pages/20630/19

**Comment by abbychau** [comment]
Thank you. I got it working.
