### ISSUE TITLE
Bug. Index page navigation menu settings does not work

### ISSUE THREAD

**Issue by AKolomoets** [ylc395/joplin-plugin-pages-publisher#5]
Joplin version 2.4.12
Plugin version: 1.2.0
OS: Windows 8.1

Steps to reproduce: 
- setup site with 2 articles
- add articles as menu items on the index page

Result: selected articles are achievable by URL, but not present on the index page.

![image](https://user-images.githubusercontent.com/47663960/137308123-18e60212-ab54-44ae-8fa7-ad6f48f58bf2.png)
![image](https://user-images.githubusercontent.com/47663960/137308292-a490caf5-145f-47f6-bb20-b6936d2c7158.png)

**Comment by ylc395** [comment]
Bugfix has been included in version 1.2.1
