### ISSUE TITLE
Publisher pane doesn't close

### ISSUE THREAD

**Issue by ImperialSquid** [ylc395/joplin-plugin-pages-publisher#6]
I'm currently having issues with the quit button not closing the pane. Clicking the quit button does nothing, the pane doesn't close, no errors, etc (if it matters the button stays highlighted as if it's being clicked). I tried running Joplin in debug mode and saw no errors in the log...

Joplin Info:
Joplin 2.5.12 (prod, win32)
Revision: 884b86f 

Pages Publisher Info:
Version: v1.6.0

**Comment by ylc395** [comment]
fixed in 1.6.1
